### PR TITLE
Make it easy to ignore quotes

### PR DESCRIPTION
**Pull request by tonyc**

### CODE REVIEW

**Review by JKtheSlacker — APPROVED** [review]
Looks pretty good to me

**Comment by rharbaugh** [comment]
Not a fan of the safe space this will generate - think of all the additional IRC traffic we might have now.
Will we have to ignore that too?




/s

**Comment by jquinby** [comment]
No objections here.

**Comment by molo1134** [comment]
Code looks good.  Please :+1: or :-1: so I can get an idea of consensus.

**Review by molo1134 — APPROVED** [review]
:+1:

**Pull request merged**
