### PR TITLE
Update fun and add toby

### PR DESCRIPTION
**Pull request by nreed97**
Made !uwu alt text  less rare and add !toby for toby coming back to the US hamvention weekend

### CODE REVIEW

**Review by katlol — APPROVED** [review]

**Comment by molo1134** [comment]
One in 20 for that uwu thing seems.. high.

And Toby isn't coming until the Sunday, I think?

**Comment by etamme** [comment]
Hi Nick, also I agree with Chris.

**Comment by rharbaugh** [comment]
tired: !uwu
inspired: !nowo

**Comment by molo1134** [comment]
closing without merge

**Pull request closed without merging**
