### PR TITLE
darksky commit - potential replacement for wx

### PR DESCRIPTION
**Pull request by jquinby**

### CODE REVIEW

**Comment by molo1134** [comment]
This solution is rather verbose.  Lets see if we can shorten it?
```

**Comment by jquinby** [comment]
That is certainly shorter and arguably more elegant.

**Comment by molo1134** [comment]
I'm not sure if it works on non-ascii values, however.

**Comment by molo1134** [comment]
Got it.
```
#!/usr/bin/perl
use utf8;
use feature 'unicode_strings';
use I18N::Langinfo qw(langinfo CODESET);
use Encode qw(decode);
binmode(STDOUT, ":utf8");
sub altCase {
    @c = split(//,shift);
    for ($i=0; $i<=$#c; $i++) {
	$c[$i] = uc($c[$i]) if $i % 2 == 0;
	$c[$i] = lc($c[$i]) if $i % 2 == 1;
    }
    return join('', @c);
}
my $codeset = langinfo(CODESET);
print(altCase(decode($codeset, join(" ", @ARGV))), "\n");
```
output:
```
$ ./mock 'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ'
ÀáÂãÄåÆçÈéÊëÌíÎïÐñÒóÔõÖ×ØùÚûÜýÞßÀáÂãÄåÆçÈéÊëÌíÎïÐñÒóÔõÖ÷ØùÚûÜýÞÿ
```

**Comment by jquinby** [comment]
Nice. I wondered about extended characters. About the only thing that would make it more snarky is colors, but maybe this is enough.

**Comment by jquinby** [comment]
The API also returns current weather alert data, if available. The jq docs show how to construct new arrays with filter results, so:

`curl -s -L --insecure "https://api.darksky.net/forecast/fapikey/38.39,-113.01?units=auto&exclude=minutely,hourly" | jq  "[.currently,.daily.summary,.alerts]"`

returns:

`[{"time":1556802891,"summary":"Clear","icon":"clear-day","nearestStormDistance":132,"nearestStormBearing":3,"precipIntensity":0,"precipProbability":0,"temperature":27.85,"apparentTemperature":27.85,"dewPoint":26.97,"humidity":0.96,"pressure":1018.1,"windSpeed":2.96,"windGust":5.47,"windBearing":182,"cloudCover":0,"uvIndex":0,"visibility":3.74,"ozone":369.27},"No precipitation throughout the week, with high temperatures peaking at 76°F on Saturday.",[{"title":"Hard Freeze Warning","regions":["Sanpete/Sevier Valleys","Southwest Utah","West Central Utah","Western Uinta Basin"],"severity":"watch","time":1556790660,"expires":1556809200,"description":"...HARD FREEZE WARNING REMAINS IN EFFECT UNTIL 9 AM MDT THIS MORNING... * AFFECTED AREA...The western Uinta Basin, Sanpete and Sevier Valleys, west central and southwest Utah. * TEMPERATURES...Falling into the upper 20s. * TIMING...Through the early morning hours today. * IMPACTS....Anyone who has early season outdoor vegetation sensitive to cold temperatures should either bring them indoors, or cover them if left outdoors.\n","uri":"https://alerts.weather.gov/cap/wwacapget.php?x=UT125CF7B488FC.HardFreezeWarning.125CF7B55F70UT.SLCNPWSLC.6989d47a4bbcfd35cef030d7ccea2ec1"},{"title":"Hard Freeze Warning","regions":["Sanpete/Sevier Valleys","Southwest Utah","West Central Utah","Western Uinta Basin"],"severity":"watch","time":1556787600,"expires":1556809200,"description":"...HARD FREEZE WARNING IN EFFECT FROM 3 AM TO 9 AM MDT THURSDAY... The National Weather Service in Salt Lake City has issued a Hard Freeze Warning, which is in effect from 3 AM to 9 AM MDT Thursday. * AFFECTED AREA...The western Uinta Basin, Sanpete and Sevier Valleys, west central and southwest Utah. * TEMPERATURES...Falling into the upper 20s. * TIMING...Late tonight into the early morning hours. * IMPACTS...Anyone who has early season outdoor vegetation sensitive to cold temperatures should either bring them indoors, or cover them if left outdoors.\n","uri":"https://alerts.weather.gov/cap/wwacapget.php?x=UT125CF7B34F50.HardFreezeWarning.125CF7B55F70UT.SLCNPWSLC.6989d47a4bbcfd35cef030d7ccea2ec1"}]]
`

Will do a bit more tweaking...for brevity's sake, probably only the title and (shortened) URI are required.

**Pull request closed without merging**
