### PR TITLE
Remove callsigns

### PR DESCRIPTION
**Pull request by DiljotSG**

### CODE REVIEW

**Comment by molo1134** [comment]
Do you represent both callsign owners in this edit?  Thanks.

**Comment by DiljotSG** [comment]
Hi, VE4NSG is my brother's callsign. I am respecting both of our wishes with this edit.

**Comment by DiljotSG** [comment]
@molo1134 Can you let me know if this is good to merge?

**Comment by DiljotSG** [comment]
@molo1134 Do you require anything further before merging this?

**Comment by DiljotSG** [comment]
@molo1134 If you want to split this into two pull requests, let me know. I can remove mine and my brother can remove his. Let me know if you would like to do things that way.

**Comment by DiljotSG** [comment]
@molo1134 is this good to go?

**Comment by DiljotSG** [comment]
@molo1134 Let me know how you want to proceed.

**Comment by molo1134** [comment]
No problem, will get you both via the other PRs. Thanks.

**Comment by DiljotSG** [comment]
Thank you so much!

--
Diljot Garcha

**Pull request closed without merging**
